#+title: Emacs Configuration
#+author: Peter Keenan
#+property: header-args:emacs-lisp :tangle /home/pk/.emacs.d/init.el

* Package initialisations

#+begin_src emacs-lisp

(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("org" . "https://orgmode.org/elpa/")
			 ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

#+end_src

Initialise use-package in non-Linux OSs

#+begin_src emacs-lisp

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

#+end_src

* UI Configuration

** Basics

This gets rid of the various menus, toolbars and the welcome screen.

#+begin_src emacs-lisp

(setq inhibit-startup-message t) 

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(set-fringe-mode 10)
(menu-bar-mode -1)
(setq visible-bell t)

#+end_src

** Font Configuration

Set the main font:

#+begin_src emacs-lisp 

(set-face-attribute 'default nil :font "Mononoki Nerd Font" :height 100)

#+end_src

And the org-mode headers:

#+begin_src emacs-lisp

(defun pk/org-font-setup ()

  (dolist (face '((org-level-1 . 1.3)
		  (org-level-2 . 1.1)
		  (org-level-3 . 1.05)
		  (org-level-4 . 1.0)
		  (org-level-5 . 1.1)
		  (org-level-6 . 1.1)
		  (org-level-7 . 1.1)
		  (org-level-8 . 1.1)))
   (set-face-attribute (car face) nil :font "Mononoki Nerd Font" :weight 'bold :height (cdr face))))

#+end_src

** Theme, Modeline and Icons 

Remember: on new machines run `M-x all-the-icons-install-fonts`, otherwise the icons won't work.

#+begin_src emacs-lisp

 (use-package doom-modeline)
   :init (doom-modeline-mode 1)

(use-package all-the-icons)

(use-package doom-themes
  :init (load-theme 'doom-palenight t))

#+end_src

** Line and column numbering

*** TODO Remember to look up the function for setting relative line numbers.

#+begin_src emacs-lisp

(column-number-mode)
(global-display-line-numbers-mode t)
(global-hl-line-mode t)

#+end_src

** Ivy

Ivy is a completion framework.

#+begin_src emacs-lisp

(use-package ivy
  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)	
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package ivy-rich
  :init
  (ivy-rich-mode 1))

#+end_src

** Counsel

#+begin_src emacs-lisp

(use-package counsel
  :bind (("M-x" . counsel-M-x)
         ("C-x b" . counsel-ibuffer)
         ("C-x C-f" . counsel-find-file)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :config
  (setq ivy-initial-inputs-alist nil)) ;; Don't start searches with ^ !

#+end_src

** Helpful

#+begin_src emacs-lisp

(use-package helpful
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  :bind
  ([remap describe-function] . counsel-describe-function)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . counsel-describe-variable)
  ([remap describe-key] . helpful-key))

#+end_src

** Which-key

#+begin_src emacs-lisp

(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 0.3))

#+end_src

** Other

=command-log-mode= creates a buffer and logs all commands

#+begin_src emacs-lisp

(use-package command-log-mode)

#+end_src

* Keybindings

** Evil

#+begin_src emacs-lisp

(use-package evil
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-want-C-u-scroll t)
  (setq evil-want-C-i-jump nil)
  :config
  (evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
  (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

  ;; Use visual line motions even outside of visual-line-mode buffers
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

  (evil-set-initial-state 'messages-buffer-mode 'normal)
  (evil-set-initial-state 'dashboard-mode 'normal))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

#+end_src

** General

For custom keybindings.

#+begin_src emacs-lisp

(use-package general)
(general-define-key
 "C-M-j" 'counsel-switch-buffer)

#+end_src

** Other

Set ESC to quit

#+begin_src emacs-lisp

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

* Org-mode

** Org-mode setup

#+begin_src emacs-lisp

(defun pk/org-mode-setup ()
  (org-indent-mode)
;; (variable-pitch-mode 1)
;; (auto-fill-mode 0)
  (visual-line-mode 1)
  (pk/org-font-setup)
  (setq evil-auto-indent nil))

#+end_src

** Org-mode main

#+begin_src emacs-lisp

(use-package org
  :hook (org-mode . pk/org-mode-setup)
  :config
  (setq org-ellipsis " ▾")

  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)
  (setq org-agenda-files 
        '("~/Documents/Org/Todo.org"
          "~/Documents/Org/SamlingExit.org"
          "/run/media/pk/Debussy/Dropbox (Samling)/Samling Team Folder/To do/Peter/2020/November.org"))

  (setq org-todo-keywords
	'((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
	  (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

  ;; It'd be good to revist the keywords and develop a system
  
  (setq org-refile-targets
    '(("Archive.org" :maxlevel . 1)))

  (setq org-capture-templates
	`(("t" "Tasks / Projects")
        ("tt" "Task" entry (file+olp "~/Documents/Org/Todo.org" "ScratchPad")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1))))
;; %?\n sets cursor at right place
;; %U\n sets timestamp
;; %a\n link to the file/line at which the capture took place
;; %i\

#+end_src

** Org bullets

#+begin_src emacs-lisp

(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

** Org-mode visual fill

This centres the main text when in org-mode, so it's not hard left.

#+begin_src emacs-lisp

(defun pk/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
	visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . pk/org-mode-visual-fill))

#+end_src

** Org-babel

This enables code to be evaluated within org-mode. Add languages to the list following =org-babel-load-languages=, but check WEBSITE for correct references.

#+begin_src emacs-lisp

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (python . t)
   (js . t)))

(setq org-confirm-babel-evaluate nil)

#+end_src

Org-tempo allows code-blocks to be autocompleted

#+begin_src emacs-lisp

(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("js" . "src js"))

#+end_src

Auto-configure babel-tangle upon saving of file

#+begin_src emacs-lisp

(defun pk/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/.emacs.d/myEmacs.org"))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'pk/org-babel-tangle-config)))

#+end_src

* Development

** Language server protocol



** Projectile

#+begin_src emacs-lisp

(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :custom ((projectile-completion-system 'ivy))
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  ;; NOTE: Set this to the folder where you keep your Git repos!
  (when (file-directory-p "~/Repos")
    (setq projectile-project-search-path '("~/Repos")))
  (setq projectile-switch-project-action #'projectile-dired))

(use-package counsel-projectile
  :config (counsel-projectile-mode))

#+end_src

** Other bits and bobs

*** Rainbow parenthesis

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

*** Commenter

#+begin_src emacs-lisp

(use-package evil-nerd-commenter
  :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

*** Loading the path for NVM's node

#+begin_src emacs-lisp

(use-package exec-path-from-shell)
(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))

(add-to-list 'exec-path "~/.nvm/versions/node/v14.15.0/bin/node")

#+end_src

** Git

Magit: Emacs' Git client

Add the following below magit block, if interested:

 :custom
 (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))



#+begin_src emacs-lisp

;;(use-package magit)

;;(use-package evil-magit
;;  :after magit)

#+end_src

Also consider *Forge*

(use-package forge)

Forge will require a token being set up at GitHub.

** LSP-mode

#+begin_src emacs-lisp

;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
(setq lsp-keymap-prefix "C-c l")

(use-package lsp-mode
    :ensure t
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
            (haskell-mode . lsp-deferred)
            (typescript-mode . lsp-deferred)
            (rjsx-mode . lsp-deferred)
            ;; if you want which-key integration
            (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp lsp-deferred)

;; optionally
(use-package lsp-ui :commands lsp-ui-mode
  :ensure t
  :commands lsp-ui-mode)
;; if you are ivy user
(use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
(use-package lsp-treemacs :commands lsp-treemacs-errors-list)

;; optionally if you want to use debugger
;; (use-package dap-mode)
;; (use-package dap-LANGUAGE) to load the dap adapter for your language


#+end_src

** Haskell mode

#+begin_src emacs-lisp

;;require 'lsp)
;;require 'lsp-haskell)
;;; Hooks so haskell and literate haskell major modes trigger LSP setup
;;add-hook 'haskell-mode-hook #'lsp)
;;add-hook 'haskell-literate-mode-hook #'lsp)

(use-package lsp-haskell
 :ensure t
 :config
 (setq lsp-haskell-process-path-hie "ghcide")
 (setq lsp-haskell-process-args-hie '())
 ;; Comment/uncomment this line to see interactions between lsp client/server.
 ;;(setq lsp-log-io t)
)

#+end_src

** Flycheck

#+begin_src emacs-lisp

(use-package flycheck
  :ensure t
  :init
  (global-flycheck-mode t))

#+end_src

** Yasnippet

#+begin_src emacs-lisp

(use-package yasnippet
  :ensure t)

#+end_src

** rjsx-mode

#+begin_src emacs-lisp

(use-package rjsx-mode
 :mode "\\.js\\'"
 :hook (rjsx-mode . lsp-deferred)
 :config
 (setq js-indent-level 2))

#+end_src

** TypeScript

#+begin_src emacs-lisp

(use-package typescript-mode
  :mode "\\.ts\\'"
  :hook (typescript-mode . lsp-deferred)
  :config
  (setq typescript-indent-level 2))

#+end_src

** Company mode

#+begin_src emacs-lisp

  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
           ("<tab>" . company-complete-selection))
          (:map lsp-mode-map
           ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0))

  (use-package company-box
    :hook (company-mode . company-box-mode))

#+end_src

** Prettier

#+begin_src emacs-lisp

(use-package prettier-js
  :ensure t
  :after (rjsx-mode)
  :hook (rjsx-mode . prettier-js-mode))

#+end_src
